version: 2.1  
  
jobs:  
  build:  
    docker:  
      - image: "circleci/python:3.6.4"  
    steps:  
      - checkout  
      - run: python cicd/hello_world.py
  
  
  unit-test:  
    docker:  
      - image: "circleci/python:3.6.4"  
    steps:  
      - checkout  
      - run:
          name: install package
          command: |
            sudo pip install -r requirements.txt 
      - run:
          name: test no redis
          no_output_timeout: 3m
          command: |
            pytest -vv --durations=10 --cov-report term-missing --cov-config=.coveragerc tests/test_something.py
  
  # something needs redis
  unit-test-with-redis:
    docker:
      - image: "circleci/python:3.6.4"  
      - image: cimg/redis:6.2.6
    steps:  
    - checkout  
    - run:
        name: install package
        command: |
          sudo pip install -r requirements-redis.txt
    - run:
        name: test redis
        no_output_timeout: 3m
        command: |
          pytest -vv --durations=10 --cov-report term-missing --cov-config=.coveragerc tests/test_redis.py


  # something needs google-bigquery
  unit-test-with-bq:
    docker:
      - image: google/cloud-sdk:359.0.0
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
      name: export key from circle ci settings
      command: echo $GCLOUD_SERVICE_KEY > /tmp/gcloud-service-key.json
    -run:
      name: setup env-variables
      command: |
          export \
          GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID} \
          GOOGLE_COMPUTE_ZONE=${GOOGLE_COMPUTE_ZONE} \
          GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcloud-service-key.json
    - run:
      name: gcp auth login
      command: |
        gcloud auth activate-service-account --key-file=${GOOGLE_APPLICATION_CREDENTIALS}
        gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
        gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
    - run:
      name: install package
      command: |
        pip install -r requirements-bq.txt 
        # sudo command is not found on cloud-sdk images
    - run:
      name: test bq 
      no_output_timeout: 5m
      command: |
        pytest -vv --durations=10 --cov-report term-missing --cov-config=.coveragerc tests/test_bq.py


  
  # something that build dockerfile

workflows:  
  build_and_test:  
    jobs:  
      - build  
      - unit-test:  
          requires:  
            - build
  build_and_test_bq_connections:  
    jobs:  
      - build  
      - unit-test-with-bq:  
          requires:  
            - build
  # trigger this using click on CircleCI UI
  unit-test-with-redis:
    jobs:
      - hold:
          type: approval
          filters:
            branches:
              ignore:
                - master
      - unit-test-with-redis:
          requires:
            - hold
