jobs:
  unit-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: set key
          command: |
            export \
            GCP_KEY_PROJECT_ID=${GCP_KEY_PROJECT_ID} \
            GCP_KEY_PRIVATE_KEY=${GCP_KEY_PRIVATE_KEY} \
      - run:
          name: gen key
          command: |
            python genkey.py
      - run:
          name: install pip
          command: |
            pip install pipenv
      - run:
          name: install package
          command: |
            pipenv sync
      - run:
          name: test
          no_output_timeout: 60m
          command: |
            ENV=CI python genenv.py
            export GOOGLE_APPLICATION_CREDENTIALS=/tmp/key.json
            export INTEGRATE_TEST=False
            pipenv run pytest --durations=10 --cov-report term-missing --cov-config=.coveragerc --cov=./data_pipeline/ tests/